-- Create Snowflake objects (databases, schemas, stages, tables) for all data sources including ClickUp insurance data
-- Co-authored with CoCo
Create database BIRD;
Create database BREVO;
Create database META;
Create database CLARITY;
Create database "3CX";
Create database ZOHO;
Create database GOOGLE_ANALYTICS;
Create database GOOGLE_ADS;
Create database CLICKUP;


Create schema BIRD.BRONZE;
Create schema BREVO.BRONZE;
Create schema META.BRONZE;
Create schema CLARITY.BRONZE;
Create schema "3CX".BRONZE;
Create schema ZOHO.BRONZE;
Create schema GOOGLE_ANALYTICS.BRONZE;
Create schema GOOGLE_ADS.BRONZE;
Create schema CLICKUP.BRONZE;

-- =============================================================================
-- STAGES: BIRD.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE BIRD.BRONZE.STG_BIRD
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Bird/MessageBird event CSVs';

-- =============================================================================
-- STAGES: BREVO.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE BREVO.BRONZE.STG_BREVO
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Brevo API extracts (CSV)';

-- =============================================================================
-- STAGES: META.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE META.BRONZE.STG_META
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Meta Marketing API extracts (CSV)';

-- =============================================================================
-- STAGES: CLARITY.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE CLARITY.BRONZE.STG_CLARITY
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Microsoft Clarity API extracts (CSV)';

-- =============================================================================
-- STAGES: 3CX.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE "3CX".BRONZE.STG_3CX
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = '3CX PBX exports (CSV)';

-- =============================================================================
-- STAGES: ZOHO.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE ZOHO.BRONZE.STG_ZOHO
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'ZOHO exports (CSV)';

-- =============================================================================
-- STAGES: GOOGLE_ANALYTICS.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Google Analytics API extracts (CSV)';

-- =============================================================================
-- STAGES: GOOGLE_ADS.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE GOOGLE_ADS.BRONZE.STG_G_ADS
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Google Ads API extracts (CSV)';

-- File format for CSV ingestion
CREATE OR REPLACE FILE FORMAT BIRD.BRONZE.FF_CSV_INFER
  TYPE = 'CSV'  PARSE_HEADER = TRUE  FIELD_OPTIONALLY_ENCLOSED_BY = '"'  SKIP_BLANK_LINES = TRUE;

-- =============================================================================
-- BIRD TABLES (25 event CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_BOUNCED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_BOUNCED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_DELIVERED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_DELIVERY_FAILED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERY_FAILED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_LINK_CLICKED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_LINK_CLICKED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_MARKED_AS_SPAM USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_MARKED_AS_SPAM.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_OPENED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_OPENED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_UNSUBSCRIBED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_UNSUBSCRIBED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_BOUNCED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_BOUNCED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_DELIVERED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_DELIVERY_FAILED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERY_FAILED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_LINKED_CLICKED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_LINKED_CLICKED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_MARKED_SPAM USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_MARKED_SPAM.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_OPENED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_OPENED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_SKIPPED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SKIPPED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_UNSUBSCRIBED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_UNSUBSCRIBED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_SUBSCRIBED_TO_LIST USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_SUBSCRIBED_TO_LIST.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_UNSUBSCRIBED_FROM_LIST USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_UNSUBSCRIBED_FROM_LIST.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_READ USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_READ.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_REPLY_CLICKED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_REPLY_CLICKED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- BREVO TABLES (6 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_AGG_REPORT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_AGG_REPORT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_CONTACT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_CONTACT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_CONTACT_LISTS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_CONTACT_LISTS.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_EVENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_EVENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_SMTP_EMAILS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EMAILS.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_SMTP_EVENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EVENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- META TABLES (9 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE META.BRONZE.META_AD_ACCOUNT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/ad_account.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_ADS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/ads.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_ADSET USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/adset.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/campaign.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_CUSTOM_AUDIENCE USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/cutom_audience.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_ACCOUNT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_account.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_AD USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_ad.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_ADSET USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_adset.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_campaign.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- CLARITY TABLES (9 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_BROWSER USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_BROWSER.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_CAMPAIGN.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_CHANNEL USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_CHANNEL.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_COUNTRY USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_COUNTRY.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_DEVICE USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_DEVICE.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_MEDIUM USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_MEDIUM.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_OS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_OS.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_SOURCE USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_SOURCE.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE CLARITY.BRONZE.CLARITY_URL USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLARITY.BRONZE.STG_CLARITY/CLARITY_URL.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- 3CX TABLES (8 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_CDR_BILLING USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/cdrbilling.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_CDR_OUTPUT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/cdroutput.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_CALL_QUALITY USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/cl_quality.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_NETWORK USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/network.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_RECORDING_PARTICIPANT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/recording_participant.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_RECORDINGS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/recordings.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_SERVICES USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/services.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE "3CX".BRONZE.TCX_SYSTEM USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@"3CX".BRONZE.STG_3CX/system.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- ZOHO TABLES (6 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE ZOHO.BRONZE.ZOHO_ACCOUNT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@ZOHO.BRONZE.STG_ZOHO/account.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE ZOHO.BRONZE.ZOHO_AGENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@ZOHO.BRONZE.STG_ZOHO/agent.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE ZOHO.BRONZE.ZOHO_CONTACT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@ZOHO.BRONZE.STG_ZOHO/contact.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE ZOHO.BRONZE.ZOHO_DEPARTMENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@ZOHO.BRONZE.STG_ZOHO/department.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE ZOHO.BRONZE.ZOHO_TASK USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@ZOHO.BRONZE.STG_ZOHO/task.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE ZOHO.BRONZE.ZOHO_TICKET USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@ZOHO.BRONZE.STG_ZOHO/ticket.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- GOOGLE ANALYTICS TABLES (7 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_300823027 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_300823027__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_347744680 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_347744680__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_300823027 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_intraday_300823027__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_347744680 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_intraday_347744680__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_300823027 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_pseudonymous_users_300823027__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_347744680 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_pseudonymous_users_347744680__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ANALYTICS.BRONZE.GA_USERS_300823027 USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_users_300823027__view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- GOOGLE ADS TABLES (17 CSVs)
-- =============================================================================

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_AD_GROUP USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_ad_group.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_AD_GROUP_AD USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_ad_group_ad.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_campaign.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_CAMPAIGN_BUDGET USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_campaign_budget.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_CONVERSION_ACTION USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_conversion_action.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_CUSTOMER USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_customer.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_KEYWORD_VIEW USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_keyword_view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_ad.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD_GROUP USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_ad_group.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_campaign.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_AGE USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_demographic_age.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_GENDER USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_demographic_gender.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_PARENTAL USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_demographic_parental.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_GEOGRAPHIC USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_geographic.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_KEYWORD USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_keyword.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_SEARCH_TERM_VIEW USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_search_term_view.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE GOOGLE_ADS.BRONZE.GADS_USER_LIST USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_user_list.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- COPY INTO: BIRD.BRONZE (25 files)
-- =============================================================================

COPY INTO BIRD.BRONZE.BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_BOUNCED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_BOUNCED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_DELIVERED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_DELIVERY_FAILED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERY_FAILED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_LINK_CLICKED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_LINK_CLICKED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_MARKED_AS_SPAM
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_MARKED_AS_SPAM.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_OPENED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_OPENED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_UNSUBSCRIBED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_UNSUBSCRIBED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_BOUNCED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_BOUNCED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_DELIVERED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_DELIVERY_FAILED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERY_FAILED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_LINKED_CLICKED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_LINKED_CLICKED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_MARKED_SPAM
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_MARKED_SPAM.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_OPENED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_OPENED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_SKIPPED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SKIPPED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_UNSUBSCRIBED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_UNSUBSCRIBED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_SUBSCRIBED_TO_LIST
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_SUBSCRIBED_TO_LIST.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_UNSUBSCRIBED_FROM_LIST
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_UNSUBSCRIBED_FROM_LIST.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_READ
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_READ.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_REPLY_CLICKED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_REPLY_CLICKED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: BREVO.BRONZE (6 files)
-- =============================================================================

COPY INTO BREVO.BRONZE.BREVO_AGG_REPORT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_AGG_REPORT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_CONTACT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_CONTACT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_CONTACT_LISTS
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_CONTACT_LISTS.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_EVENT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_EVENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_SMTP_EMAILS
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EMAILS.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_SMTP_EVENT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EVENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: META.BRONZE (9 files)
-- =============================================================================

COPY INTO META.BRONZE.META_AD_ACCOUNT
  FROM @META.BRONZE.STG_META/ad_account.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_ADS
  FROM @META.BRONZE.STG_META/ads.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_ADSET
  FROM @META.BRONZE.STG_META/adset.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_CAMPAIGN
  FROM @META.BRONZE.STG_META/campaign.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_CUSTOM_AUDIENCE
  FROM @META.BRONZE.STG_META/cutom_audience.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_ACCOUNT
  FROM @META.BRONZE.STG_META/insight_account.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_AD
  FROM @META.BRONZE.STG_META/insight_ad.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_ADSET
  FROM @META.BRONZE.STG_META/insight_adset.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_CAMPAIGN
  FROM @META.BRONZE.STG_META/insight_campaign.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: CLARITY.BRONZE (9 files)
-- =============================================================================

COPY INTO CLARITY.BRONZE.CLARITY_BROWSER
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_BROWSER.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_CAMPAIGN
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_CAMPAIGN.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_CHANNEL
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_CHANNEL.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_COUNTRY
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_COUNTRY.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_DEVICE
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_DEVICE.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_MEDIUM
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_MEDIUM.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_OS
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_OS.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_SOURCE
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_SOURCE.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO CLARITY.BRONZE.CLARITY_URL
  FROM @CLARITY.BRONZE.STG_CLARITY/CLARITY_URL.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: 3CX.BRONZE (8 files)
-- =============================================================================

COPY INTO "3CX".BRONZE.TCX_CDR_BILLING
  FROM @"3CX".BRONZE.STG_3CX/cdrbilling.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_CDR_OUTPUT
  FROM @"3CX".BRONZE.STG_3CX/cdroutput.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_CALL_QUALITY
  FROM @"3CX".BRONZE.STG_3CX/cl_quality.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_NETWORK
  FROM @"3CX".BRONZE.STG_3CX/network.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_RECORDING_PARTICIPANT
  FROM @"3CX".BRONZE.STG_3CX/recording_participant.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_RECORDINGS
  FROM @"3CX".BRONZE.STG_3CX/recordings.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_SERVICES
  FROM @"3CX".BRONZE.STG_3CX/services.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO "3CX".BRONZE.TCX_SYSTEM
  FROM @"3CX".BRONZE.STG_3CX/system.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: ZOHO.BRONZE (6 files)
-- =============================================================================

COPY INTO ZOHO.BRONZE.ZOHO_ACCOUNT
  FROM @ZOHO.BRONZE.STG_ZOHO/account.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO ZOHO.BRONZE.ZOHO_AGENT
  FROM @ZOHO.BRONZE.STG_ZOHO/agent.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO ZOHO.BRONZE.ZOHO_CONTACT
  FROM @ZOHO.BRONZE.STG_ZOHO/contact.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO ZOHO.BRONZE.ZOHO_DEPARTMENT
  FROM @ZOHO.BRONZE.STG_ZOHO/department.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO ZOHO.BRONZE.ZOHO_TASK
  FROM @ZOHO.BRONZE.STG_ZOHO/task.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO ZOHO.BRONZE.ZOHO_TICKET
  FROM @ZOHO.BRONZE.STG_ZOHO/ticket.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: GOOGLE_ANALYTICS.BRONZE (7 files)
-- =============================================================================

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_300823027
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_300823027__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_347744680
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_347744680__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_300823027
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_intraday_300823027__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_347744680
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_analytics_intraday_347744680__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_300823027
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_pseudonymous_users_300823027__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_347744680
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_pseudonymous_users_347744680__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ANALYTICS.BRONZE.GA_USERS_300823027
  FROM @GOOGLE_ANALYTICS.BRONZE.STG_G_ANALYTICS/google_analytics_users_300823027__view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- COPY INTO: GOOGLE_ADS.BRONZE (17 files)
-- =============================================================================

COPY INTO GOOGLE_ADS.BRONZE.GADS_AD_GROUP
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_ad_group.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_AD_GROUP_AD
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_ad_group_ad.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_CAMPAIGN
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_campaign.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_CAMPAIGN_BUDGET
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_campaign_budget.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_CONVERSION_ACTION
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_conversion_action.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_CUSTOMER
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_customer.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_KEYWORD_VIEW
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_keyword_view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_ad.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD_GROUP
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_ad_group.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_CAMPAIGN
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_campaign.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_AGE
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_demographic_age.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_GENDER
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_demographic_gender.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_PARENTAL
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_demographic_parental.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_GEOGRAPHIC
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_geographic.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_KEYWORD
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_performance_report_keyword.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_SEARCH_TERM_VIEW
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_search_term_view.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO GOOGLE_ADS.BRONZE.GADS_USER_LIST
  FROM @GOOGLE_ADS.BRONZE.STG_G_ADS/google_ads_user_list.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- STAGES: CLICKUP.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE CLICKUP.BRONZE.STG_CLICKUP
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'ClickUp insurance task exports (CSV)';

-- =============================================================================
-- CLICKUP TABLES (1 CSV)
-- =============================================================================

CREATE OR REPLACE TABLE CLICKUP.BRONZE.CLICKUP_INSURANCE_TASKS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@CLICKUP.BRONZE.STG_CLICKUP/clickup_insurance_data.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

-- =============================================================================
-- COPY INTO: CLICKUP.BRONZE (1 file)
-- =============================================================================

COPY INTO CLICKUP.BRONZE.CLICKUP_INSURANCE_TASKS
  FROM @CLICKUP.BRONZE.STG_CLICKUP/clickup_insurance_data.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- VERIFY: Row counts for all tables
-- =============================================================================

SELECT 'BIRD.BRONZE.BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM BIRD.BRONZE.BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_BOUNCED', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_BOUNCED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_DELIVERED', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_DELIVERED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_DELIVERY_FAILED', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_DELIVERY_FAILED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_LINK_CLICKED', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_LINK_CLICKED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_MARKED_AS_SPAM', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_MARKED_AS_SPAM
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_OPENED', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_OPENED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_SENT', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_SENT
UNION ALL SELECT 'BIRD.BRONZE.BIRD_EMAIL_UNSUBSCRIBED', COUNT(*) FROM BIRD.BRONZE.BIRD_EMAIL_UNSUBSCRIBED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_BOUNCED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_BOUNCED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_DELIVERED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_DELIVERED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_DELIVERY_FAILED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_DELIVERY_FAILED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_LINKED_CLICKED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_LINKED_CLICKED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_MARKED_SPAM', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_MARKED_SPAM
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_OPENED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_OPENED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_SENT', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_SENT
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_SKIPPED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_SKIPPED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_MESSAGE_UNSUBSCRIBED', COUNT(*) FROM BIRD.BRONZE.BIRD_MESSAGE_UNSUBSCRIBED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_SUBSCRIBED_TO_LIST', COUNT(*) FROM BIRD.BRONZE.BIRD_SUBSCRIBED_TO_LIST
UNION ALL SELECT 'BIRD.BRONZE.BIRD_UNSUBSCRIBED_FROM_LIST', COUNT(*) FROM BIRD.BRONZE.BIRD_UNSUBSCRIBED_FROM_LIST
UNION ALL SELECT 'BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERED', COUNT(*) FROM BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED', COUNT(*) FROM BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED
UNION ALL SELECT 'BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_READ', COUNT(*) FROM BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_READ
UNION ALL SELECT 'BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_SENT', COUNT(*) FROM BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_SENT
UNION ALL SELECT 'BIRD.BRONZE.BIRD_WHATSAPP_REPLY_CLICKED', COUNT(*) FROM BIRD.BRONZE.BIRD_WHATSAPP_REPLY_CLICKED
UNION ALL SELECT 'BREVO.BRONZE.BREVO_AGG_REPORT', COUNT(*) FROM BREVO.BRONZE.BREVO_AGG_REPORT
UNION ALL SELECT 'BREVO.BRONZE.BREVO_CONTACT', COUNT(*) FROM BREVO.BRONZE.BREVO_CONTACT
UNION ALL SELECT 'BREVO.BRONZE.BREVO_CONTACT_LISTS', COUNT(*) FROM BREVO.BRONZE.BREVO_CONTACT_LISTS
UNION ALL SELECT 'BREVO.BRONZE.BREVO_EVENT', COUNT(*) FROM BREVO.BRONZE.BREVO_EVENT
UNION ALL SELECT 'BREVO.BRONZE.BREVO_SMTP_EMAILS', COUNT(*) FROM BREVO.BRONZE.BREVO_SMTP_EMAILS
UNION ALL SELECT 'BREVO.BRONZE.BREVO_SMTP_EVENT', COUNT(*) FROM BREVO.BRONZE.BREVO_SMTP_EVENT
UNION ALL SELECT 'META.BRONZE.META_AD_ACCOUNT', COUNT(*) FROM META.BRONZE.META_AD_ACCOUNT
UNION ALL SELECT 'META.BRONZE.META_ADS', COUNT(*) FROM META.BRONZE.META_ADS
UNION ALL SELECT 'META.BRONZE.META_ADSET', COUNT(*) FROM META.BRONZE.META_ADSET
UNION ALL SELECT 'META.BRONZE.META_CAMPAIGN', COUNT(*) FROM META.BRONZE.META_CAMPAIGN
UNION ALL SELECT 'META.BRONZE.META_CUSTOM_AUDIENCE', COUNT(*) FROM META.BRONZE.META_CUSTOM_AUDIENCE
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_ACCOUNT', COUNT(*) FROM META.BRONZE.META_INSIGHT_ACCOUNT
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_AD', COUNT(*) FROM META.BRONZE.META_INSIGHT_AD
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_ADSET', COUNT(*) FROM META.BRONZE.META_INSIGHT_ADSET
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_CAMPAIGN', COUNT(*) FROM META.BRONZE.META_INSIGHT_CAMPAIGN
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_BROWSER', COUNT(*) FROM CLARITY.BRONZE.CLARITY_BROWSER
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_CAMPAIGN', COUNT(*) FROM CLARITY.BRONZE.CLARITY_CAMPAIGN
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_CHANNEL', COUNT(*) FROM CLARITY.BRONZE.CLARITY_CHANNEL
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_COUNTRY', COUNT(*) FROM CLARITY.BRONZE.CLARITY_COUNTRY
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_DEVICE', COUNT(*) FROM CLARITY.BRONZE.CLARITY_DEVICE
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_MEDIUM', COUNT(*) FROM CLARITY.BRONZE.CLARITY_MEDIUM
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_OS', COUNT(*) FROM CLARITY.BRONZE.CLARITY_OS
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_SOURCE', COUNT(*) FROM CLARITY.BRONZE.CLARITY_SOURCE
UNION ALL SELECT 'CLARITY.BRONZE.CLARITY_URL', COUNT(*) FROM CLARITY.BRONZE.CLARITY_URL
UNION ALL SELECT '3CX.BRONZE.TCX_CDR_BILLING', COUNT(*) FROM "3CX".BRONZE.TCX_CDR_BILLING
UNION ALL SELECT '3CX.BRONZE.TCX_CDR_OUTPUT', COUNT(*) FROM "3CX".BRONZE.TCX_CDR_OUTPUT
UNION ALL SELECT '3CX.BRONZE.TCX_CALL_QUALITY', COUNT(*) FROM "3CX".BRONZE.TCX_CALL_QUALITY
UNION ALL SELECT '3CX.BRONZE.TCX_NETWORK', COUNT(*) FROM "3CX".BRONZE.TCX_NETWORK
UNION ALL SELECT '3CX.BRONZE.TCX_RECORDING_PARTICIPANT', COUNT(*) FROM "3CX".BRONZE.TCX_RECORDING_PARTICIPANT
UNION ALL SELECT '3CX.BRONZE.TCX_RECORDINGS', COUNT(*) FROM "3CX".BRONZE.TCX_RECORDINGS
UNION ALL SELECT '3CX.BRONZE.TCX_SERVICES', COUNT(*) FROM "3CX".BRONZE.TCX_SERVICES
UNION ALL SELECT '3CX.BRONZE.TCX_SYSTEM', COUNT(*) FROM "3CX".BRONZE.TCX_SYSTEM
UNION ALL SELECT 'ZOHO.BRONZE.ZOHO_ACCOUNT', COUNT(*) FROM ZOHO.BRONZE.ZOHO_ACCOUNT
UNION ALL SELECT 'ZOHO.BRONZE.ZOHO_AGENT', COUNT(*) FROM ZOHO.BRONZE.ZOHO_AGENT
UNION ALL SELECT 'ZOHO.BRONZE.ZOHO_CONTACT', COUNT(*) FROM ZOHO.BRONZE.ZOHO_CONTACT
UNION ALL SELECT 'ZOHO.BRONZE.ZOHO_DEPARTMENT', COUNT(*) FROM ZOHO.BRONZE.ZOHO_DEPARTMENT
UNION ALL SELECT 'ZOHO.BRONZE.ZOHO_TASK', COUNT(*) FROM ZOHO.BRONZE.ZOHO_TASK
UNION ALL SELECT 'ZOHO.BRONZE.ZOHO_TICKET', COUNT(*) FROM ZOHO.BRONZE.ZOHO_TICKET
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_300823027', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_300823027
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_347744680', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_347744680
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_300823027', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_300823027
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_347744680', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_ANALYTICS_INTRADAY_347744680
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_300823027', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_300823027
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_347744680', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_PSEUDONYMOUS_USERS_347744680
UNION ALL SELECT 'GOOGLE_ANALYTICS.BRONZE.GA_USERS_300823027', COUNT(*) FROM GOOGLE_ANALYTICS.BRONZE.GA_USERS_300823027
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_AD_GROUP', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_AD_GROUP
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_AD_GROUP_AD', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_AD_GROUP_AD
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_CAMPAIGN', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_CAMPAIGN
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_CAMPAIGN_BUDGET', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_CAMPAIGN_BUDGET
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_CONVERSION_ACTION', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_CONVERSION_ACTION
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_CUSTOMER', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_CUSTOMER
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_KEYWORD_VIEW', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_KEYWORD_VIEW
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD_GROUP', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_AD_GROUP
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_CAMPAIGN', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_CAMPAIGN
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_AGE', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_AGE
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_GENDER', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_GENDER
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_PARENTAL', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_DEMO_PARENTAL
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_GEOGRAPHIC', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_GEOGRAPHIC
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_KEYWORD', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_PERF_REPORT_KEYWORD
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_SEARCH_TERM_VIEW', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_SEARCH_TERM_VIEW
UNION ALL SELECT 'GOOGLE_ADS.BRONZE.GADS_USER_LIST', COUNT(*) FROM GOOGLE_ADS.BRONZE.GADS_USER_LIST
UNION ALL SELECT 'CLICKUP.BRONZE.CLICKUP_INSURANCE_TASKS', COUNT(*) FROM CLICKUP.BRONZE.CLICKUP_INSURANCE_TASKS
ORDER BY TABLE_NAME;

