alter schema BIRD.RAW RENAME TO BIRD.BRONZE;

alter schema BREVO.RAW RENAME TO BREVO.BRONZE;

alter schema CLARITY.RAW RENAME TO CLARITY.BRONZE;

alter schema GOOGLE_ADS.RAW RENAME TO GOOGLE_ADS.BRONZE;

alter schema GOOGLE_ANALYTICS.RAW RENAME TO GOOGLE_ANALYTICS.BRONZE;

alter schema META.RAW RENAME TO META.BRONZE;

alter schema MY_ALFRED_CRM.RAW RENAME TO MY_ALFRED_CRM.BRONZE;

alter schema "3CX".RAW RENAME TO "3CX".BRONZE;

alter schema ZOHO.RAW RENAME TO ZOHO.BRONZE;






