-- Meta Bronze layer: database, stage, table creation via INFER_SCHEMA, and CSV loading
-- Co-authored with CoCo

--Database Creation 
Create or replace database META;

--Schema Creation
Create or replace schema META.BRONZE;


--Stage Creation
CREATE OR REPLACE STAGE META.BRONZE.STG_META
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Meta Marketing API extracts (CSV)';


-- File Format Creation 
CREATE OR REPLACE FILE FORMAT AAA.PUBLIC.FF_CSV_INFER
TYPE = 'CSV'  PARSE_HEADER = TRUE  FIELD_OPTIONALLY_ENCLOSED_BY = '"'  SKIP_BLANK_LINES = TRUE;



--Table Creation at bronze layer

CREATE OR REPLACE TABLE META.BRONZE.META_AD_ACCOUNT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/ad_account.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_ADS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/ads.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_ADSET USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/adset.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/campaign.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_CUSTOM_AUDIENCE USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/cutom_audience.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_ACCOUNT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_account.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_AD USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_ad.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_ADSET USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_adset.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));

CREATE OR REPLACE TABLE META.BRONZE.META_INSIGHT_CAMPAIGN USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@META.BRONZE.STG_META/insight_campaign.csv',
    FILE_FORMAT => 'AAA.PUBLIC.FF_CSV_INFER')));




-- Loading data into tables from stage

COPY INTO META.BRONZE.META_AD_ACCOUNT
  FROM @META.BRONZE.STG_META/ad_account.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_ADS
  FROM @META.BRONZE.STG_META/ads.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_ADSET
  FROM @META.BRONZE.STG_META/adset.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_CAMPAIGN
  FROM @META.BRONZE.STG_META/campaign.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_CUSTOM_AUDIENCE
  FROM @META.BRONZE.STG_META/cutom_audience.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_ACCOUNT
  FROM @META.BRONZE.STG_META/insight_account.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_AD
  FROM @META.BRONZE.STG_META/insight_ad.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_ADSET
  FROM @META.BRONZE.STG_META/insight_adset.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO META.BRONZE.META_INSIGHT_CAMPAIGN
  FROM @META.BRONZE.STG_META/insight_campaign.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';


-- ============================================================
-- VALIDATION: Verify record counts after loading
-- ============================================================

SELECT 'META_AD_ACCOUNT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM META.BRONZE.META_AD_ACCOUNT
UNION ALL
SELECT 'META_ADS', COUNT(*) FROM META.BRONZE.META_ADS
UNION ALL
SELECT 'META_ADSET', COUNT(*) FROM META.BRONZE.META_ADSET
UNION ALL
SELECT 'META_CAMPAIGN', COUNT(*) FROM META.BRONZE.META_CAMPAIGN
UNION ALL
SELECT 'META_CUSTOM_AUDIENCE', COUNT(*) FROM META.BRONZE.META_CUSTOM_AUDIENCE
UNION ALL
SELECT 'META_INSIGHT_ACCOUNT', COUNT(*) FROM META.BRONZE.META_INSIGHT_ACCOUNT
UNION ALL
SELECT 'META_INSIGHT_AD', COUNT(*) FROM META.BRONZE.META_INSIGHT_AD
UNION ALL
SELECT 'META_INSIGHT_ADSET', COUNT(*) FROM META.BRONZE.META_INSIGHT_ADSET
UNION ALL
SELECT 'META_INSIGHT_CAMPAIGN', COUNT(*) FROM META.BRONZE.META_INSIGHT_CAMPAIGN;


-- VALIDATION: Confirm no empty tables (fail-safe check)
SELECT TABLE_NAME, ROW_COUNT
  FROM META.INFORMATION_SCHEMA.TABLES
  WHERE TABLE_SCHEMA = 'BRONZE'
    AND ROW_COUNT = 0
  ORDER BY TABLE_NAME;

  