-- Meta Silver layer: incremental MERGE from Bronze streams into Silver tables
-- Co-authored with CoCo
-- =============================================================================
-- META ADS SOURCE | SILVER LAYER
-- Incremental MERGE via streams (Bronze -> Silver)
-- Source: META.BRONZE -> META.SILVER
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS META.SILVER;

-- =============================================================================
-- STEP 1: TARGET TABLES
-- =============================================================================

CREATE OR REPLACE TABLE META.SILVER.SLV_AD_ACCOUNT (
    ACCOUNT_ID          NUMBER          NOT NULL PRIMARY KEY,
    ACCOUNT_ID_TEXT     VARCHAR,
    ACCOUNT_NAME        VARCHAR,
    ACCOUNT_STATUS      NUMBER,
    CURRENCY            VARCHAR,
    TIMEZONE_NAME       VARCHAR,
    SPEND_CAP           NUMBER,
    AMOUNT_SPENT        NUMBER,
    BALANCE             NUMBER,
    BUSINESS_ID         NUMBER,
    BUSINESS_NAME       VARCHAR,
    IS_VALID_RECORD     BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE META.SILVER.SLV_CAMPAIGN (
    CAMPAIGN_ID         NUMBER          NOT NULL PRIMARY KEY,
    CAMPAIGN_NAME       VARCHAR,
    STATUS              VARCHAR,
    EFFECTIVE_STATUS    VARCHAR,
    OBJECTIVE           VARCHAR,
    BUYING_TYPE         VARCHAR,
    DAILY_BUDGET        NUMBER,
    LIFETIME_BUDGET     NUMBER,
    BUDGET_REMAINING    BOOLEAN,
    SPECIAL_AD_CATEGORIES VARCHAR,
    CREATED_TIME        TIMESTAMP_NTZ,
    START_TIME          TIMESTAMP_NTZ,
    STOP_TIME           TIMESTAMP_NTZ,
    UPDATED_TIME        TIMESTAMP_NTZ,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE META.SILVER.SLV_ADSET (
    ADSET_ID            NUMBER          NOT NULL PRIMARY KEY,
    ADSET_NAME          VARCHAR,
    CAMPAIGN_ID         NUMBER,
    STATUS              VARCHAR,
    EFFECTIVE_STATUS    VARCHAR,
    BID_STRATEGY        VARCHAR,
    BID_AMOUNT          NUMBER,
    BILLING_EVENT       VARCHAR,
    OPTIMIZATION_GOAL   VARCHAR,
    DESTINATION_TYPE    VARCHAR,
    DAILY_BUDGET        NUMBER,
    LIFETIME_BUDGET     NUMBER,
    START_TIME          TIMESTAMP_NTZ,
    END_TIME            TIMESTAMP_NTZ,
    UPDATED_TIME        TIMESTAMP_NTZ,
    TARGETING_RAW       VARCHAR,
    PROMOTED_OBJECT_RAW VARCHAR,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE META.SILVER.SLV_AD (
    AD_ID               NUMBER          NOT NULL PRIMARY KEY,
    AD_NAME             VARCHAR,
    ADSET_ID            NUMBER,
    CAMPAIGN_ID         NUMBER,
    STATUS              VARCHAR,
    EFFECTIVE_STATUS    VARCHAR,
    CREATIVE_ID         NUMBER,
    CREATIVE_NAME       VARCHAR,
    CREATIVE_TITLE      VARCHAR,
    CREATIVE_BODY       VARCHAR,
    CREATIVE_IMAGE_URL  VARCHAR,
    CREATIVE_CTA_TYPE   VARCHAR,
    CREATED_TIME        TIMESTAMP_NTZ,
    UPDATED_TIME        TIMESTAMP_NTZ,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE META.SILVER.SLV_CUSTOM_AUDIENCE (
    AUDIENCE_ID         NUMBER          NOT NULL PRIMARY KEY,
    AUDIENCE_NAME       VARCHAR,
    DESCRIPTION         VARCHAR,
    SUBTYPE             VARCHAR,
    APPROX_COUNT_LOWER  NUMBER,
    APPROX_COUNT_UPPER  NUMBER,
    RETENTION_DAYS      NUMBER,
    DELIVERY_STATUS_CODE NUMBER,
    DELIVERY_STATUS_DESC VARCHAR,
    DATA_SOURCE_TYPE    VARCHAR,
    DATA_SOURCE_SUB_TYPE VARCHAR,
    LOOKALIKE_SPEC_RAW  VARCHAR,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE META.SILVER.SLV_INSIGHT_ACCOUNT (
    DATE_START          DATE            NOT NULL,
    DATE_STOP           DATE            NOT NULL,
    IMPRESSIONS         NUMBER,
    REACH               NUMBER,
    CLICKS              NUMBER,
    SPEND               NUMBER,
    CPC                 NUMBER,
    CPM                 NUMBER,
    CTR                 NUMBER,
    FREQUENCY           NUMBER,
    ACTIONS_RAW         VARCHAR,
    ACTION_VALUES_RAW   VARCHAR,
    AD_ACCOUNT_ID       NUMBER          NOT NULL,
    IS_VALID_RECORD     BOOLEAN,
    IS_VALID_DATE_RANGE BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ,
    PRIMARY KEY (AD_ACCOUNT_ID, DATE_START, DATE_STOP)
);

CREATE OR REPLACE TABLE META.SILVER.SLV_INSIGHT_CAMPAIGN (
    CAMPAIGN_ID         NUMBER          NOT NULL,
    CAMPAIGN_NAME       VARCHAR,
    DATE_START          DATE            NOT NULL,
    DATE_STOP           DATE            NOT NULL,
    IMPRESSIONS         NUMBER,
    REACH               NUMBER,
    CLICKS              NUMBER,
    SPEND               NUMBER,
    CPC                 NUMBER,
    CPM                 NUMBER,
    CTR                 NUMBER,
    ACTIONS_RAW         VARCHAR,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    IS_VALID_DATE_RANGE BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ,
    PRIMARY KEY (CAMPAIGN_ID, DATE_START, DATE_STOP)
);

CREATE OR REPLACE TABLE META.SILVER.SLV_INSIGHT_ADSET (
    ADSET_ID            NUMBER          NOT NULL,
    ADSET_NAME          VARCHAR,
    CAMPAIGN_ID         NUMBER,
    DATE_START          DATE            NOT NULL,
    DATE_STOP           DATE            NOT NULL,
    IMPRESSIONS         NUMBER,
    REACH               NUMBER,
    CLICKS              NUMBER,
    SPEND               NUMBER,
    CPC                 NUMBER,
    CPM                 NUMBER,
    CTR                 NUMBER,
    ACTIONS_RAW         VARCHAR,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    IS_VALID_DATE_RANGE BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ,
    PRIMARY KEY (ADSET_ID, DATE_START, DATE_STOP)
);

CREATE OR REPLACE TABLE META.SILVER.SLV_INSIGHT_AD (
    AD_ID               NUMBER          NOT NULL,
    AD_NAME             VARCHAR,
    ADSET_ID            NUMBER,
    CAMPAIGN_ID         NUMBER,
    DATE_START          DATE            NOT NULL,
    DATE_STOP           DATE            NOT NULL,
    IMPRESSIONS         NUMBER,
    REACH               NUMBER,
    CLICKS              NUMBER,
    SPEND               NUMBER,
    CPC                 NUMBER,
    CPM                 NUMBER,
    CTR                 NUMBER,
    ACTIONS_RAW         VARCHAR,
    AD_ACCOUNT_ID       NUMBER,
    IS_VALID_RECORD     BOOLEAN,
    IS_VALID_DATE_RANGE BOOLEAN,
    AUDIT_INSERTED_AT   TIMESTAMP_NTZ,
    AUDIT_UPDATED_AT    TIMESTAMP_NTZ,
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    BATCH_ID            VARCHAR,
    SILVER_LOADED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SILVER_UPDATED_AT   TIMESTAMP_NTZ,
    PRIMARY KEY (AD_ID, DATE_START, DATE_STOP)
);

-- =============================================================================
-- STEP 2: STREAMS on Bronze tables
-- =============================================================================

ALTER TABLE META.BRONZE.META_AD_ACCOUNT SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_CAMPAIGN SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_ADSET SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_ADS SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_CUSTOM_AUDIENCE SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_INSIGHT_ACCOUNT SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_INSIGHT_CAMPAIGN SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_INSIGHT_ADSET SET CHANGE_TRACKING = TRUE;
ALTER TABLE META.BRONZE.META_INSIGHT_AD SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_AD_ACCOUNT
    ON TABLE META.BRONZE.META_AD_ACCOUNT
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_CAMPAIGN
    ON TABLE META.BRONZE.META_CAMPAIGN
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_ADSET
    ON TABLE META.BRONZE.META_ADSET
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_ADS
    ON TABLE META.BRONZE.META_ADS
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_CUSTOM_AUDIENCE
    ON TABLE META.BRONZE.META_CUSTOM_AUDIENCE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_INSIGHT_ACCOUNT
    ON TABLE META.BRONZE.META_INSIGHT_ACCOUNT
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_INSIGHT_CAMPAIGN
    ON TABLE META.BRONZE.META_INSIGHT_CAMPAIGN
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_INSIGHT_ADSET
    ON TABLE META.BRONZE.META_INSIGHT_ADSET
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM META.BRONZE.STREAM_META_INSIGHT_AD
    ON TABLE META.BRONZE.META_INSIGHT_AD
    SHOW_INITIAL_ROWS = TRUE;

-- =============================================================================
-- STEP 3: MERGE PROCEDURES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- MERGE_SLV_AD_ACCOUNT
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_AD_ACCOUNT()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_AD_ACCOUNT AS tgt
    USING (
        SELECT
            ACCOUNT_ID,
            ID                              AS ACCOUNT_ID_TEXT,
            TRIM(NAME)                      AS ACCOUNT_NAME,
            ACCOUNT_STATUS,
            TRIM(CURRENCY)                  AS CURRENCY,
            TRIM(TIMEZONE_NAME)             AS TIMEZONE_NAME,
            SPEND_CAP, AMOUNT_SPENT, BALANCE, BUSINESS_ID,
            TRIM(BUSINESS_NAME)             AS BUSINESS_NAME,
            CASE WHEN ACCOUNT_ID IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT)  AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED                AS IS_DELETED,
            BATCH_ID
        FROM META.BRONZE.STREAM_META_AD_ACCOUNT
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.ACCOUNT_ID = src.ACCOUNT_ID
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.ACCOUNT_ID_TEXT = src.ACCOUNT_ID_TEXT, tgt.ACCOUNT_NAME = src.ACCOUNT_NAME,
            tgt.ACCOUNT_STATUS = src.ACCOUNT_STATUS, tgt.CURRENCY = src.CURRENCY,
            tgt.TIMEZONE_NAME = src.TIMEZONE_NAME, tgt.SPEND_CAP = src.SPEND_CAP,
            tgt.AMOUNT_SPENT = src.AMOUNT_SPENT, tgt.BALANCE = src.BALANCE,
            tgt.BUSINESS_ID = src.BUSINESS_ID, tgt.BUSINESS_NAME = src.BUSINESS_NAME,
            tgt.IS_VALID_RECORD = src.IS_VALID_RECORD, tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT,
            tgt.IS_DELETED = src.IS_DELETED, tgt.BATCH_ID = src.BATCH_ID,
            tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (ACCOUNT_ID, ACCOUNT_ID_TEXT, ACCOUNT_NAME, ACCOUNT_STATUS, CURRENCY,
                TIMEZONE_NAME, SPEND_CAP, AMOUNT_SPENT, BALANCE, BUSINESS_ID, BUSINESS_NAME,
                IS_VALID_RECORD, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.ACCOUNT_ID, src.ACCOUNT_ID_TEXT, src.ACCOUNT_NAME, src.ACCOUNT_STATUS,
                src.CURRENCY, src.TIMEZONE_NAME, src.SPEND_CAP, src.AMOUNT_SPENT, src.BALANCE,
                src.BUSINESS_ID, src.BUSINESS_NAME, src.IS_VALID_RECORD,
                src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT, src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_AD_ACCOUNT completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_CAMPAIGN
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_CAMPAIGN()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_CAMPAIGN AS tgt
    USING (
        SELECT
            ID                              AS CAMPAIGN_ID,
            TRIM(NAME)                      AS CAMPAIGN_NAME,
            TRIM(STATUS)                    AS STATUS,
            TRIM(EFFECTIVE_STATUS)          AS EFFECTIVE_STATUS,
            TRIM(OBJECTIVE)                 AS OBJECTIVE,
            TRIM(BUYING_TYPE)               AS BUYING_TYPE,
            DAILY_BUDGET, LIFETIME_BUDGET, BUDGET_REMAINING,
            TRIM(SPECIAL_AD_CATEGORIES)     AS SPECIAL_AD_CATEGORIES,
            TRY_TO_TIMESTAMP_NTZ(CREATED_TIME) AS CREATED_TIME,
            TRY_TO_TIMESTAMP_NTZ(START_TIME)   AS START_TIME,
            TRY_TO_TIMESTAMP_NTZ(STOP_TIME)    AS STOP_TIME,
            TRY_TO_TIMESTAMP_NTZ(UPDATED_TIME) AS UPDATED_TIME,
            AD_ACCOUNT_ID,
            CASE WHEN ID IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT)  AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED                AS IS_DELETED,
            BATCH_ID
        FROM META.BRONZE.STREAM_META_CAMPAIGN
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.CAMPAIGN_ID = src.CAMPAIGN_ID
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.CAMPAIGN_NAME = src.CAMPAIGN_NAME, tgt.STATUS = src.STATUS,
            tgt.EFFECTIVE_STATUS = src.EFFECTIVE_STATUS, tgt.OBJECTIVE = src.OBJECTIVE,
            tgt.BUYING_TYPE = src.BUYING_TYPE, tgt.DAILY_BUDGET = src.DAILY_BUDGET,
            tgt.LIFETIME_BUDGET = src.LIFETIME_BUDGET, tgt.BUDGET_REMAINING = src.BUDGET_REMAINING,
            tgt.SPECIAL_AD_CATEGORIES = src.SPECIAL_AD_CATEGORIES,
            tgt.CREATED_TIME = src.CREATED_TIME, tgt.START_TIME = src.START_TIME,
            tgt.STOP_TIME = src.STOP_TIME, tgt.UPDATED_TIME = src.UPDATED_TIME,
            tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID, tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (CAMPAIGN_ID, CAMPAIGN_NAME, STATUS, EFFECTIVE_STATUS, OBJECTIVE, BUYING_TYPE,
                DAILY_BUDGET, LIFETIME_BUDGET, BUDGET_REMAINING, SPECIAL_AD_CATEGORIES,
                CREATED_TIME, START_TIME, STOP_TIME, UPDATED_TIME, AD_ACCOUNT_ID,
                IS_VALID_RECORD, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.CAMPAIGN_ID, src.CAMPAIGN_NAME, src.STATUS, src.EFFECTIVE_STATUS,
                src.OBJECTIVE, src.BUYING_TYPE, src.DAILY_BUDGET, src.LIFETIME_BUDGET,
                src.BUDGET_REMAINING, src.SPECIAL_AD_CATEGORIES, src.CREATED_TIME,
                src.START_TIME, src.STOP_TIME, src.UPDATED_TIME, src.AD_ACCOUNT_ID,
                src.IS_VALID_RECORD, src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT,
                src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_CAMPAIGN completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_ADSET
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_ADSET()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_ADSET AS tgt
    USING (
        SELECT
            ID AS ADSET_ID, TRIM(NAME) AS ADSET_NAME, CAMPAIGN_ID,
            TRIM(STATUS) AS STATUS, TRIM(EFFECTIVE_STATUS) AS EFFECTIVE_STATUS,
            TRIM(BID_STRATEGY) AS BID_STRATEGY, BID_AMOUNT,
            TRIM(BILLING_EVENT) AS BILLING_EVENT, TRIM(OPTIMIZATION_GOAL) AS OPTIMIZATION_GOAL,
            TRIM(DESTINATION_TYPE) AS DESTINATION_TYPE, DAILY_BUDGET, LIFETIME_BUDGET,
            TRY_TO_TIMESTAMP_NTZ(START_TIME) AS START_TIME,
            TRY_TO_TIMESTAMP_NTZ(END_TIME) AS END_TIME,
            TRY_TO_TIMESTAMP_NTZ(UPDATED_TIME) AS UPDATED_TIME,
            TARGETING AS TARGETING_RAW, PROMOTED_OBJECT AS PROMOTED_OBJECT_RAW,
            AD_ACCOUNT_ID,
            CASE WHEN ID IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_ADSET
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.ADSET_ID = src.ADSET_ID
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.ADSET_NAME = src.ADSET_NAME, tgt.CAMPAIGN_ID = src.CAMPAIGN_ID,
            tgt.STATUS = src.STATUS, tgt.EFFECTIVE_STATUS = src.EFFECTIVE_STATUS,
            tgt.BID_STRATEGY = src.BID_STRATEGY, tgt.BID_AMOUNT = src.BID_AMOUNT,
            tgt.BILLING_EVENT = src.BILLING_EVENT, tgt.OPTIMIZATION_GOAL = src.OPTIMIZATION_GOAL,
            tgt.DESTINATION_TYPE = src.DESTINATION_TYPE, tgt.DAILY_BUDGET = src.DAILY_BUDGET,
            tgt.LIFETIME_BUDGET = src.LIFETIME_BUDGET, tgt.START_TIME = src.START_TIME,
            tgt.END_TIME = src.END_TIME, tgt.UPDATED_TIME = src.UPDATED_TIME,
            tgt.TARGETING_RAW = src.TARGETING_RAW, tgt.PROMOTED_OBJECT_RAW = src.PROMOTED_OBJECT_RAW,
            tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID, tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (ADSET_ID, ADSET_NAME, CAMPAIGN_ID, STATUS, EFFECTIVE_STATUS, BID_STRATEGY,
                BID_AMOUNT, BILLING_EVENT, OPTIMIZATION_GOAL, DESTINATION_TYPE,
                DAILY_BUDGET, LIFETIME_BUDGET, START_TIME, END_TIME, UPDATED_TIME,
                TARGETING_RAW, PROMOTED_OBJECT_RAW, AD_ACCOUNT_ID,
                IS_VALID_RECORD, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.ADSET_ID, src.ADSET_NAME, src.CAMPAIGN_ID, src.STATUS, src.EFFECTIVE_STATUS,
                src.BID_STRATEGY, src.BID_AMOUNT, src.BILLING_EVENT, src.OPTIMIZATION_GOAL,
                src.DESTINATION_TYPE, src.DAILY_BUDGET, src.LIFETIME_BUDGET,
                src.START_TIME, src.END_TIME, src.UPDATED_TIME,
                src.TARGETING_RAW, src.PROMOTED_OBJECT_RAW, src.AD_ACCOUNT_ID,
                src.IS_VALID_RECORD, src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT,
                src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_ADSET completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_AD
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_AD()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_AD AS tgt
    USING (
        SELECT
            ID AS AD_ID, TRIM(NAME) AS AD_NAME, ADSET_ID, CAMPAIGN_ID,
            TRIM(STATUS) AS STATUS, TRIM(EFFECTIVE_STATUS) AS EFFECTIVE_STATUS,
            CREATIVE_ID, TRIM(CREATIVE_NAME) AS CREATIVE_NAME,
            TRIM(CREATIVE_TITLE) AS CREATIVE_TITLE, TRIM(CREATIVE_BODY) AS CREATIVE_BODY,
            TRIM(CREATIVE_IMAGE_URL) AS CREATIVE_IMAGE_URL,
            TRIM(CREATIVE_CTA_TYPE) AS CREATIVE_CTA_TYPE,
            TRY_TO_TIMESTAMP_NTZ(CREATED_TIME) AS CREATED_TIME,
            TRY_TO_TIMESTAMP_NTZ(UPDATED_TIME) AS UPDATED_TIME,
            AD_ACCOUNT_ID,
            CASE WHEN ID IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_ADS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.AD_ID = src.AD_ID
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.AD_NAME = src.AD_NAME, tgt.ADSET_ID = src.ADSET_ID,
            tgt.CAMPAIGN_ID = src.CAMPAIGN_ID, tgt.STATUS = src.STATUS,
            tgt.EFFECTIVE_STATUS = src.EFFECTIVE_STATUS, tgt.CREATIVE_ID = src.CREATIVE_ID,
            tgt.CREATIVE_NAME = src.CREATIVE_NAME, tgt.CREATIVE_TITLE = src.CREATIVE_TITLE,
            tgt.CREATIVE_BODY = src.CREATIVE_BODY, tgt.CREATIVE_IMAGE_URL = src.CREATIVE_IMAGE_URL,
            tgt.CREATIVE_CTA_TYPE = src.CREATIVE_CTA_TYPE, tgt.CREATED_TIME = src.CREATED_TIME,
            tgt.UPDATED_TIME = src.UPDATED_TIME, tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID,
            tgt.IS_VALID_RECORD = src.IS_VALID_RECORD, tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT,
            tgt.IS_DELETED = src.IS_DELETED, tgt.BATCH_ID = src.BATCH_ID,
            tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (AD_ID, AD_NAME, ADSET_ID, CAMPAIGN_ID, STATUS, EFFECTIVE_STATUS,
                CREATIVE_ID, CREATIVE_NAME, CREATIVE_TITLE, CREATIVE_BODY,
                CREATIVE_IMAGE_URL, CREATIVE_CTA_TYPE, CREATED_TIME, UPDATED_TIME,
                AD_ACCOUNT_ID, IS_VALID_RECORD, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.AD_ID, src.AD_NAME, src.ADSET_ID, src.CAMPAIGN_ID, src.STATUS,
                src.EFFECTIVE_STATUS, src.CREATIVE_ID, src.CREATIVE_NAME, src.CREATIVE_TITLE,
                src.CREATIVE_BODY, src.CREATIVE_IMAGE_URL, src.CREATIVE_CTA_TYPE,
                src.CREATED_TIME, src.UPDATED_TIME, src.AD_ACCOUNT_ID,
                src.IS_VALID_RECORD, src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT,
                src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_AD completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_CUSTOM_AUDIENCE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_CUSTOM_AUDIENCE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_CUSTOM_AUDIENCE AS tgt
    USING (
        SELECT
            ID AS AUDIENCE_ID, TRIM(NAME) AS AUDIENCE_NAME, TRIM(DESCRIPTION) AS DESCRIPTION,
            TRIM(SUBTYPE) AS SUBTYPE, APPROX_COUNT_LOWER, APPROX_COUNT_UPPER,
            RETENTION_DAYS, DELIVERY_STATUS_CODE, TRIM(DELIVERY_STATUS_DESC) AS DELIVERY_STATUS_DESC,
            TRIM(DATA_SOURCE_TYPE) AS DATA_SOURCE_TYPE, TRIM(DATA_SOURCE_SUB_TYPE) AS DATA_SOURCE_SUB_TYPE,
            LOOKALIKE_SPEC AS LOOKALIKE_SPEC_RAW, AD_ACCOUNT_ID,
            CASE WHEN ID IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_CUSTOM_AUDIENCE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.AUDIENCE_ID = src.AUDIENCE_ID
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.AUDIENCE_NAME = src.AUDIENCE_NAME, tgt.DESCRIPTION = src.DESCRIPTION,
            tgt.SUBTYPE = src.SUBTYPE, tgt.APPROX_COUNT_LOWER = src.APPROX_COUNT_LOWER,
            tgt.APPROX_COUNT_UPPER = src.APPROX_COUNT_UPPER, tgt.RETENTION_DAYS = src.RETENTION_DAYS,
            tgt.DELIVERY_STATUS_CODE = src.DELIVERY_STATUS_CODE,
            tgt.DELIVERY_STATUS_DESC = src.DELIVERY_STATUS_DESC,
            tgt.DATA_SOURCE_TYPE = src.DATA_SOURCE_TYPE,
            tgt.DATA_SOURCE_SUB_TYPE = src.DATA_SOURCE_SUB_TYPE,
            tgt.LOOKALIKE_SPEC_RAW = src.LOOKALIKE_SPEC_RAW,
            tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID, tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (AUDIENCE_ID, AUDIENCE_NAME, DESCRIPTION, SUBTYPE, APPROX_COUNT_LOWER,
                APPROX_COUNT_UPPER, RETENTION_DAYS, DELIVERY_STATUS_CODE, DELIVERY_STATUS_DESC,
                DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE, LOOKALIKE_SPEC_RAW, AD_ACCOUNT_ID,
                IS_VALID_RECORD, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.AUDIENCE_ID, src.AUDIENCE_NAME, src.DESCRIPTION, src.SUBTYPE,
                src.APPROX_COUNT_LOWER, src.APPROX_COUNT_UPPER, src.RETENTION_DAYS,
                src.DELIVERY_STATUS_CODE, src.DELIVERY_STATUS_DESC, src.DATA_SOURCE_TYPE,
                src.DATA_SOURCE_SUB_TYPE, src.LOOKALIKE_SPEC_RAW, src.AD_ACCOUNT_ID,
                src.IS_VALID_RECORD, src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT,
                src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_CUSTOM_AUDIENCE completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_INSIGHT_ACCOUNT
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_INSIGHT_ACCOUNT()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_INSIGHT_ACCOUNT AS tgt
    USING (
        SELECT
            DATE_START, DATE_STOP, IMPRESSIONS, REACH, CLICKS, SPEND, CPC, CPM, CTR, FREQUENCY,
            ACTIONS AS ACTIONS_RAW, ACTION_VALUES AS ACTION_VALUES_RAW, AD_ACCOUNT_ID,
            CASE WHEN DATE_START IS NULL OR AD_ACCOUNT_ID IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            CASE WHEN DATE_START IS NULL OR DATE_STOP IS NULL THEN FALSE
                 WHEN DATE_START > DATE_STOP THEN FALSE
                 WHEN DATE_START > CURRENT_DATE() THEN FALSE ELSE TRUE END AS IS_VALID_DATE_RANGE,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_INSIGHT_ACCOUNT
        QUALIFY ROW_NUMBER() OVER (PARTITION BY AD_ACCOUNT_ID, DATE_START, DATE_STOP ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID AND tgt.DATE_START = src.DATE_START AND tgt.DATE_STOP = src.DATE_STOP
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.IMPRESSIONS = src.IMPRESSIONS, tgt.REACH = src.REACH, tgt.CLICKS = src.CLICKS,
            tgt.SPEND = src.SPEND, tgt.CPC = src.CPC, tgt.CPM = src.CPM, tgt.CTR = src.CTR,
            tgt.FREQUENCY = src.FREQUENCY, tgt.ACTIONS_RAW = src.ACTIONS_RAW,
            tgt.ACTION_VALUES_RAW = src.ACTION_VALUES_RAW,
            tgt.IS_VALID_RECORD = src.IS_VALID_RECORD, tgt.IS_VALID_DATE_RANGE = src.IS_VALID_DATE_RANGE,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (DATE_START, DATE_STOP, IMPRESSIONS, REACH, CLICKS, SPEND, CPC, CPM, CTR,
                FREQUENCY, ACTIONS_RAW, ACTION_VALUES_RAW, AD_ACCOUNT_ID,
                IS_VALID_RECORD, IS_VALID_DATE_RANGE, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.DATE_START, src.DATE_STOP, src.IMPRESSIONS, src.REACH, src.CLICKS,
                src.SPEND, src.CPC, src.CPM, src.CTR, src.FREQUENCY,
                src.ACTIONS_RAW, src.ACTION_VALUES_RAW, src.AD_ACCOUNT_ID,
                src.IS_VALID_RECORD, src.IS_VALID_DATE_RANGE,
                src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT, src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_INSIGHT_ACCOUNT completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_INSIGHT_CAMPAIGN
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_INSIGHT_CAMPAIGN()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_INSIGHT_CAMPAIGN AS tgt
    USING (
        SELECT
            CAMPAIGN_ID, TRIM(CAMPAIGN_NAME) AS CAMPAIGN_NAME,
            DATE_START, DATE_STOP, IMPRESSIONS, REACH, CLICKS, SPEND, CPC, CPM, CTR,
            ACTIONS AS ACTIONS_RAW, AD_ACCOUNT_ID,
            CASE WHEN CAMPAIGN_ID IS NULL OR DATE_START IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            CASE WHEN DATE_START IS NULL OR DATE_STOP IS NULL THEN FALSE
                 WHEN DATE_START > DATE_STOP THEN FALSE
                 WHEN DATE_START > CURRENT_DATE() THEN FALSE ELSE TRUE END AS IS_VALID_DATE_RANGE,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_INSIGHT_CAMPAIGN
        QUALIFY ROW_NUMBER() OVER (PARTITION BY CAMPAIGN_ID, DATE_START, DATE_STOP ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.CAMPAIGN_ID = src.CAMPAIGN_ID AND tgt.DATE_START = src.DATE_START AND tgt.DATE_STOP = src.DATE_STOP
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.CAMPAIGN_NAME = src.CAMPAIGN_NAME, tgt.IMPRESSIONS = src.IMPRESSIONS,
            tgt.REACH = src.REACH, tgt.CLICKS = src.CLICKS, tgt.SPEND = src.SPEND,
            tgt.CPC = src.CPC, tgt.CPM = src.CPM, tgt.CTR = src.CTR,
            tgt.ACTIONS_RAW = src.ACTIONS_RAW, tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID,
            tgt.IS_VALID_RECORD = src.IS_VALID_RECORD, tgt.IS_VALID_DATE_RANGE = src.IS_VALID_DATE_RANGE,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (CAMPAIGN_ID, CAMPAIGN_NAME, DATE_START, DATE_STOP, IMPRESSIONS, REACH,
                CLICKS, SPEND, CPC, CPM, CTR, ACTIONS_RAW, AD_ACCOUNT_ID,
                IS_VALID_RECORD, IS_VALID_DATE_RANGE, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.CAMPAIGN_ID, src.CAMPAIGN_NAME, src.DATE_START, src.DATE_STOP,
                src.IMPRESSIONS, src.REACH, src.CLICKS, src.SPEND, src.CPC, src.CPM, src.CTR,
                src.ACTIONS_RAW, src.AD_ACCOUNT_ID, src.IS_VALID_RECORD, src.IS_VALID_DATE_RANGE,
                src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT, src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_INSIGHT_CAMPAIGN completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_INSIGHT_ADSET
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_INSIGHT_ADSET()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_INSIGHT_ADSET AS tgt
    USING (
        SELECT
            ADSET_ID, TRIM(ADSET_NAME) AS ADSET_NAME, CAMPAIGN_ID,
            DATE_START, DATE_STOP, IMPRESSIONS, REACH, CLICKS, SPEND, CPC, CPM, CTR,
            ACTIONS AS ACTIONS_RAW, AD_ACCOUNT_ID,
            CASE WHEN ADSET_ID IS NULL OR DATE_START IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            CASE WHEN DATE_START IS NULL OR DATE_STOP IS NULL THEN FALSE
                 WHEN DATE_START > DATE_STOP THEN FALSE
                 WHEN DATE_START > CURRENT_DATE() THEN FALSE ELSE TRUE END AS IS_VALID_DATE_RANGE,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_INSIGHT_ADSET
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ADSET_ID, DATE_START, DATE_STOP ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.ADSET_ID = src.ADSET_ID AND tgt.DATE_START = src.DATE_START AND tgt.DATE_STOP = src.DATE_STOP
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.ADSET_NAME = src.ADSET_NAME, tgt.CAMPAIGN_ID = src.CAMPAIGN_ID,
            tgt.IMPRESSIONS = src.IMPRESSIONS, tgt.REACH = src.REACH, tgt.CLICKS = src.CLICKS,
            tgt.SPEND = src.SPEND, tgt.CPC = src.CPC, tgt.CPM = src.CPM, tgt.CTR = src.CTR,
            tgt.ACTIONS_RAW = src.ACTIONS_RAW, tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID,
            tgt.IS_VALID_RECORD = src.IS_VALID_RECORD, tgt.IS_VALID_DATE_RANGE = src.IS_VALID_DATE_RANGE,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (ADSET_ID, ADSET_NAME, CAMPAIGN_ID, DATE_START, DATE_STOP, IMPRESSIONS, REACH,
                CLICKS, SPEND, CPC, CPM, CTR, ACTIONS_RAW, AD_ACCOUNT_ID,
                IS_VALID_RECORD, IS_VALID_DATE_RANGE, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.ADSET_ID, src.ADSET_NAME, src.CAMPAIGN_ID, src.DATE_START, src.DATE_STOP,
                src.IMPRESSIONS, src.REACH, src.CLICKS, src.SPEND, src.CPC, src.CPM, src.CTR,
                src.ACTIONS_RAW, src.AD_ACCOUNT_ID, src.IS_VALID_RECORD, src.IS_VALID_DATE_RANGE,
                src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT, src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_INSIGHT_ADSET completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- -----------------------------------------------------------------------------
-- MERGE_SLV_INSIGHT_AD
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE META.SILVER.MERGE_SLV_INSIGHT_AD()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO META.SILVER.SLV_INSIGHT_AD AS tgt
    USING (
        SELECT
            AD_ID, TRIM(AD_NAME) AS AD_NAME, ADSET_ID, CAMPAIGN_ID,
            DATE_START, DATE_STOP, IMPRESSIONS, REACH, CLICKS, SPEND, CPC, CPM, CTR,
            ACTIONS AS ACTIONS_RAW, AD_ACCOUNT_ID,
            CASE WHEN AD_ID IS NULL OR DATE_START IS NULL THEN FALSE ELSE TRUE END AS IS_VALID_RECORD,
            CASE WHEN DATE_START IS NULL OR DATE_STOP IS NULL THEN FALSE
                 WHEN DATE_START > DATE_STOP THEN FALSE
                 WHEN DATE_START > CURRENT_DATE() THEN FALSE ELSE TRUE END AS IS_VALID_DATE_RANGE,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_INSERTED_AT) AS AUDIT_INSERTED_AT,
            TRY_TO_TIMESTAMP_NTZ(AUDIT_UPDATED_AT) AS AUDIT_UPDATED_AT,
            AUDIT_IS_DELETED AS IS_DELETED, BATCH_ID
        FROM META.BRONZE.STREAM_META_INSIGHT_AD
        QUALIFY ROW_NUMBER() OVER (PARTITION BY AD_ID, DATE_START, DATE_STOP ORDER BY AUDIT_UPDATED_AT DESC NULLS LAST) = 1
    ) AS src
    ON tgt.AD_ID = src.AD_ID AND tgt.DATE_START = src.DATE_START AND tgt.DATE_STOP = src.DATE_STOP
    WHEN MATCHED AND src.IS_DELETED = TRUE THEN
        UPDATE SET tgt.IS_DELETED = TRUE, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND (tgt.AUDIT_UPDATED_AT < src.AUDIT_UPDATED_AT OR tgt.AUDIT_UPDATED_AT IS NULL) THEN
        UPDATE SET
            tgt.AD_NAME = src.AD_NAME, tgt.ADSET_ID = src.ADSET_ID, tgt.CAMPAIGN_ID = src.CAMPAIGN_ID,
            tgt.IMPRESSIONS = src.IMPRESSIONS, tgt.REACH = src.REACH, tgt.CLICKS = src.CLICKS,
            tgt.SPEND = src.SPEND, tgt.CPC = src.CPC, tgt.CPM = src.CPM, tgt.CTR = src.CTR,
            tgt.ACTIONS_RAW = src.ACTIONS_RAW, tgt.AD_ACCOUNT_ID = src.AD_ACCOUNT_ID,
            tgt.IS_VALID_RECORD = src.IS_VALID_RECORD, tgt.IS_VALID_DATE_RANGE = src.IS_VALID_DATE_RANGE,
            tgt.AUDIT_UPDATED_AT = src.AUDIT_UPDATED_AT, tgt.IS_DELETED = src.IS_DELETED,
            tgt.BATCH_ID = src.BATCH_ID, tgt.SILVER_UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.IS_DELETED = FALSE THEN
        INSERT (AD_ID, AD_NAME, ADSET_ID, CAMPAIGN_ID, DATE_START, DATE_STOP, IMPRESSIONS,
                REACH, CLICKS, SPEND, CPC, CPM, CTR, ACTIONS_RAW, AD_ACCOUNT_ID,
                IS_VALID_RECORD, IS_VALID_DATE_RANGE, AUDIT_INSERTED_AT, AUDIT_UPDATED_AT, IS_DELETED, BATCH_ID)
        VALUES (src.AD_ID, src.AD_NAME, src.ADSET_ID, src.CAMPAIGN_ID, src.DATE_START,
                src.DATE_STOP, src.IMPRESSIONS, src.REACH, src.CLICKS, src.SPEND,
                src.CPC, src.CPM, src.CTR, src.ACTIONS_RAW, src.AD_ACCOUNT_ID,
                src.IS_VALID_RECORD, src.IS_VALID_DATE_RANGE,
                src.AUDIT_INSERTED_AT, src.AUDIT_UPDATED_AT, src.IS_DELETED, src.BATCH_ID);
    RETURN 'MERGE_SLV_INSIGHT_AD completed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 4: DATA QUALITY VIEW
-- =============================================================================
CREATE OR REPLACE VIEW META.SILVER.V_DATA_QUALITY_SUMMARY AS
SELECT 'SLV_AD_ACCOUNT' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN IS_VALID_RECORD AND NOT IS_DELETED THEN 1 ELSE 0 END) AS VALID_ACTIVE_ROWS,
    NULL AS VALID_EMAILS,
    SUM(CASE WHEN IS_DELETED THEN 1 ELSE 0 END) AS DELETED_ROWS,
    ROUND(SUM(CASE WHEN IS_VALID_RECORD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS VALIDITY_PCT
FROM META.SILVER.SLV_AD_ACCOUNT
UNION ALL
SELECT 'SLV_CAMPAIGN', COUNT(*),
    SUM(CASE WHEN IS_VALID_RECORD AND NOT IS_DELETED THEN 1 ELSE 0 END), NULL,
    SUM(CASE WHEN IS_DELETED THEN 1 ELSE 0 END),
    ROUND(SUM(CASE WHEN IS_VALID_RECORD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2)
FROM META.SILVER.SLV_CAMPAIGN
UNION ALL
SELECT 'SLV_ADSET', COUNT(*),
    SUM(CASE WHEN IS_VALID_RECORD AND NOT IS_DELETED THEN 1 ELSE 0 END), NULL,
    SUM(CASE WHEN IS_DELETED THEN 1 ELSE 0 END),
    ROUND(SUM(CASE WHEN IS_VALID_RECORD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2)
FROM META.SILVER.SLV_ADSET
UNION ALL
SELECT 'SLV_AD', COUNT(*),
    SUM(CASE WHEN IS_VALID_RECORD AND NOT IS_DELETED THEN 1 ELSE 0 END), NULL,
    SUM(CASE WHEN IS_DELETED THEN 1 ELSE 0 END),
    ROUND(SUM(CASE WHEN IS_VALID_RECORD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2)
FROM META.SILVER.SLV_AD
UNION ALL
SELECT 'SLV_CUSTOM_AUDIENCE', COUNT(*),
    SUM(CASE WHEN IS_VALID_RECORD AND NOT IS_DELETED THEN 1 ELSE 0 END), NULL,
    SUM(CASE WHEN IS_DELETED THEN 1 ELSE 0 END),
    ROUND(SUM(CASE WHEN IS_VALID_RECORD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2)
FROM META.SILVER.SLV_CUSTOM_AUDIENCE
UNION ALL
SELECT 'SLV_INSIGHT_AD', COUNT(*),
    SUM(CASE WHEN IS_VALID_RECORD AND IS_VALID_DATE_RANGE AND NOT IS_DELETED THEN 1 ELSE 0 END),
    SUM(CASE WHEN IS_VALID_DATE_RANGE THEN 1 ELSE 0 END),
    SUM(CASE WHEN IS_DELETED THEN 1 ELSE 0 END),
    ROUND(SUM(CASE WHEN IS_VALID_RECORD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2)
FROM META.SILVER.SLV_INSIGHT_AD;

-- =============================================================================
-- STEP 5: EXECUTE (call procedures to load data)
-- =============================================================================
CALL META.SILVER.MERGE_SLV_AD_ACCOUNT();
CALL META.SILVER.MERGE_SLV_CAMPAIGN();
CALL META.SILVER.MERGE_SLV_ADSET();
CALL META.SILVER.MERGE_SLV_AD();
CALL META.SILVER.MERGE_SLV_CUSTOM_AUDIENCE();
CALL META.SILVER.MERGE_SLV_INSIGHT_ACCOUNT();
CALL META.SILVER.MERGE_SLV_INSIGHT_CAMPAIGN();
CALL META.SILVER.MERGE_SLV_INSIGHT_ADSET();
CALL META.SILVER.MERGE_SLV_INSIGHT_AD();

-- Verify
SELECT * FROM META.SILVER.V_DATA_QUALITY_SUMMARY;
