-- Meta pipeline validation: end-to-end checks across Bronze, Silver, and Gold layers
-- Co-authored with CoCo
-- =============================================================================
-- META ADS SOURCE | DEMO VALIDATION
-- Run this to verify the entire pipeline is working end-to-end
-- =============================================================================

-- =============================================================================
-- CHECK 1: Bronze Layer — Row Counts
-- =============================================================================

SELECT 'META.BRONZE.META_AD_ACCOUNT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM META.BRONZE.META_AD_ACCOUNT
UNION ALL SELECT 'META.BRONZE.META_CAMPAIGN', COUNT(*) FROM META.BRONZE.META_CAMPAIGN
UNION ALL SELECT 'META.BRONZE.META_ADSET', COUNT(*) FROM META.BRONZE.META_ADSET
UNION ALL SELECT 'META.BRONZE.META_ADS', COUNT(*) FROM META.BRONZE.META_ADS
UNION ALL SELECT 'META.BRONZE.META_CUSTOM_AUDIENCE', COUNT(*) FROM META.BRONZE.META_CUSTOM_AUDIENCE
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_ACCOUNT', COUNT(*) FROM META.BRONZE.META_INSIGHT_ACCOUNT
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_CAMPAIGN', COUNT(*) FROM META.BRONZE.META_INSIGHT_CAMPAIGN
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_ADSET', COUNT(*) FROM META.BRONZE.META_INSIGHT_ADSET
UNION ALL SELECT 'META.BRONZE.META_INSIGHT_AD', COUNT(*) FROM META.BRONZE.META_INSIGHT_AD
ORDER BY TABLE_NAME;

-- =============================================================================
-- CHECK 2: Silver Layer — Row Counts
-- =============================================================================

SELECT 'META.SILVER.SLV_AD_ACCOUNT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM META.SILVER.SLV_AD_ACCOUNT
UNION ALL SELECT 'META.SILVER.SLV_CAMPAIGN', COUNT(*) FROM META.SILVER.SLV_CAMPAIGN
UNION ALL SELECT 'META.SILVER.SLV_ADSET', COUNT(*) FROM META.SILVER.SLV_ADSET
UNION ALL SELECT 'META.SILVER.SLV_AD', COUNT(*) FROM META.SILVER.SLV_AD
UNION ALL SELECT 'META.SILVER.SLV_CUSTOM_AUDIENCE', COUNT(*) FROM META.SILVER.SLV_CUSTOM_AUDIENCE
UNION ALL SELECT 'META.SILVER.SLV_INSIGHT_ACCOUNT', COUNT(*) FROM META.SILVER.SLV_INSIGHT_ACCOUNT
UNION ALL SELECT 'META.SILVER.SLV_INSIGHT_CAMPAIGN', COUNT(*) FROM META.SILVER.SLV_INSIGHT_CAMPAIGN
UNION ALL SELECT 'META.SILVER.SLV_INSIGHT_ADSET', COUNT(*) FROM META.SILVER.SLV_INSIGHT_ADSET
UNION ALL SELECT 'META.SILVER.SLV_INSIGHT_AD', COUNT(*) FROM META.SILVER.SLV_INSIGHT_AD
ORDER BY TABLE_NAME;

-- =============================================================================
-- CHECK 3: Gold Layer — Row Counts
-- =============================================================================

SELECT 'META.GOLD.DIM_AD_ACCOUNT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM META.GOLD.DIM_AD_ACCOUNT
UNION ALL SELECT 'META.GOLD.DIM_CAMPAIGN', COUNT(*) FROM META.GOLD.DIM_CAMPAIGN
UNION ALL SELECT 'META.GOLD.DIM_ADSET', COUNT(*) FROM META.GOLD.DIM_ADSET
UNION ALL SELECT 'META.GOLD.DIM_AD', COUNT(*) FROM META.GOLD.DIM_AD
UNION ALL SELECT 'META.GOLD.DIM_DATE', COUNT(*) FROM META.GOLD.DIM_DATE
UNION ALL SELECT 'META.GOLD.FACT_AD_INSIGHT', COUNT(*) FROM META.GOLD.FACT_AD_INSIGHT
ORDER BY TABLE_NAME;

-- =============================================================================
-- CHECK 4: Data Quality Summary (Silver)
-- =============================================================================

SELECT * FROM META.SILVER.V_DATA_QUALITY_SUMMARY;

-- =============================================================================
-- CHECK 5: Streams Status — Have data pending?
-- =============================================================================

SELECT 'STREAM_META_AD_ACCOUNT' AS STREAM_NAME, SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_AD_ACCOUNT') AS HAS_DATA
UNION ALL SELECT 'STREAM_META_CAMPAIGN', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_CAMPAIGN')
UNION ALL SELECT 'STREAM_META_ADSET', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_ADSET')
UNION ALL SELECT 'STREAM_META_ADS', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_ADS')
UNION ALL SELECT 'STREAM_META_CUSTOM_AUDIENCE', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_CUSTOM_AUDIENCE')
UNION ALL SELECT 'STREAM_META_INSIGHT_ACCOUNT', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_INSIGHT_ACCOUNT')
UNION ALL SELECT 'STREAM_META_INSIGHT_CAMPAIGN', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_INSIGHT_CAMPAIGN')
UNION ALL SELECT 'STREAM_META_INSIGHT_ADSET', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_INSIGHT_ADSET')
UNION ALL SELECT 'STREAM_META_INSIGHT_AD', SYSTEM$STREAM_HAS_DATA('META.BRONZE.STREAM_META_INSIGHT_AD');

-- =============================================================================
-- CHECK 6: Gold Star Schema — Sample Fact with Dimensions
-- =============================================================================

SELECT
    f.INSIGHT_SK,
    dac.ACCOUNT_NAME,
    dc.CAMPAIGN_NAME,
    dc.OBJECTIVE,
    das.ADSET_NAME,
    das.OPTIMIZATION_GOAL,
    da.AD_NAME,
    da.CREATIVE_TITLE,
    dd.DATE_ID AS REPORT_DATE,
    dd.DAY_NAME,
    f.IMPRESSIONS,
    f.REACH,
    f.CLICKS,
    f.SPEND,
    f.CTR,
    f.CPC,
    f.CPM
FROM META.GOLD.FACT_AD_INSIGHT f
LEFT JOIN META.GOLD.DIM_AD_ACCOUNT dac ON f.DIM_AD_ACCOUNT_SK = dac.DIM_AD_ACCOUNT_SK
LEFT JOIN META.GOLD.DIM_CAMPAIGN dc ON f.DIM_CAMPAIGN_SK = dc.DIM_CAMPAIGN_SK
LEFT JOIN META.GOLD.DIM_ADSET das ON f.DIM_ADSET_SK = das.DIM_ADSET_SK
LEFT JOIN META.GOLD.DIM_AD da ON f.DIM_AD_SK = da.DIM_AD_SK
LEFT JOIN META.GOLD.DIM_DATE dd ON f.DATE_START_ID = dd.DATE_ID
ORDER BY f.SPEND DESC
LIMIT 20;

-- =============================================================================
-- CHECK 7: Marketing Analytics — Campaign Performance Summary
-- =============================================================================

SELECT
    dc.CAMPAIGN_NAME,
    dc.OBJECTIVE,
    dc.STATUS,
    COUNT(DISTINCT f.AD_ID) AS TOTAL_ADS,
    SUM(f.IMPRESSIONS) AS TOTAL_IMPRESSIONS,
    SUM(f.REACH) AS TOTAL_REACH,
    SUM(f.CLICKS) AS TOTAL_CLICKS,
    SUM(f.SPEND) AS TOTAL_SPEND,
    ROUND(SUM(f.CLICKS) * 100.0 / NULLIF(SUM(f.IMPRESSIONS), 0), 2) AS AVG_CTR,
    ROUND(SUM(f.SPEND) / NULLIF(SUM(f.CLICKS), 0), 2) AS AVG_CPC,
    ROUND(SUM(f.SPEND) * 1000.0 / NULLIF(SUM(f.IMPRESSIONS), 0), 2) AS AVG_CPM
FROM META.GOLD.FACT_AD_INSIGHT f
JOIN META.GOLD.DIM_CAMPAIGN dc ON f.DIM_CAMPAIGN_SK = dc.DIM_CAMPAIGN_SK
GROUP BY dc.CAMPAIGN_NAME, dc.OBJECTIVE, dc.STATUS
ORDER BY TOTAL_SPEND DESC
LIMIT 20;

-- =============================================================================
-- CHECK 8: Task Execution History (last 1 hour)
-- =============================================================================

SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(META.INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD(HOUR, -1, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 30
))
ORDER BY COMPLETED_TIME DESC;
