-- Creates Brevo database, stage, tables (via INFER_SCHEMA), and loads CSVs from stage
-- Co-authored with CoCo
-- =============================================================================
-- IM PILOT PROJECT | BREVO SOURCE | BRONZE LAYER SETUP
-- Requires CSV files to be on @BREVO.BRONZE.STG_BREVO before running
-- =============================================================================

CREATE OR REPLACE DATABASE BREVO;

CREATE OR REPLACE SCHEMA BREVO.BRONZE;

-- =============================================================================
-- STAGES: BREVO.BRONZE
-- =============================================================================
CREATE OR REPLACE STAGE BREVO.BRONZE.STG_BREVO
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Brevo API extracts (CSV)';

-- File format for CSV ingestion
CREATE OR REPLACE FILE FORMAT BREVO.BRONZE.FF_CSV_BREVO
  TYPE = 'CSV'
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_BLANK_LINES = TRUE;

-- =============================================================================
-- BREVO TABLES (6 CSVs) - Created via INFER_SCHEMA
-- NOTE: CSVs must already be on @BREVO.BRONZE.STG_BREVO before running this
-- =============================================================================

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_AGG_REPORT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_AGG_REPORT.csv',
    FILE_FORMAT => 'BREVO.BRONZE.FF_CSV_BREVO')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_CONTACT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_CONTACT.csv',
    FILE_FORMAT => 'BREVO.BRONZE.FF_CSV_BREVO')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_CONTACT_LISTS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_CONTACT_LISTS.csv',
    FILE_FORMAT => 'BREVO.BRONZE.FF_CSV_BREVO')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_EVENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_EVENT.csv',
    FILE_FORMAT => 'BREVO.BRONZE.FF_CSV_BREVO')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_SMTP_EMAILS USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EMAILS.csv',
    FILE_FORMAT => 'BREVO.BRONZE.FF_CSV_BREVO')));

CREATE OR REPLACE TABLE BREVO.BRONZE.BREVO_SMTP_EVENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EVENT.csv',
    FILE_FORMAT => 'BREVO.BRONZE.FF_CSV_BREVO')));

-- =============================================================================
-- COPY INTO: BREVO.BRONZE (6 files)
-- =============================================================================

COPY INTO BREVO.BRONZE.BREVO_AGG_REPORT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_AGG_REPORT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_BLANK_LINES=TRUE)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_CONTACT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_CONTACT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_BLANK_LINES=TRUE)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_CONTACT_LISTS
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_CONTACT_LISTS.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_BLANK_LINES=TRUE)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_EVENT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_EVENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_BLANK_LINES=TRUE)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_SMTP_EMAILS
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EMAILS.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_BLANK_LINES=TRUE)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BREVO.BRONZE.BREVO_SMTP_EVENT
  FROM @BREVO.BRONZE.STG_BREVO/BREVO_SMTP_EVENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_BLANK_LINES=TRUE)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- VERIFY: Row counts for all tables
-- =============================================================================

SELECT 'BREVO.BRONZE.BREVO_AGG_REPORT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM BREVO.BRONZE.BREVO_AGG_REPORT
UNION ALL SELECT 'BREVO.BRONZE.BREVO_CONTACT', COUNT(*) FROM BREVO.BRONZE.BREVO_CONTACT
UNION ALL SELECT 'BREVO.BRONZE.BREVO_CONTACT_LISTS', COUNT(*) FROM BREVO.BRONZE.BREVO_CONTACT_LISTS
UNION ALL SELECT 'BREVO.BRONZE.BREVO_EVENT', COUNT(*) FROM BREVO.BRONZE.BREVO_EVENT
UNION ALL SELECT 'BREVO.BRONZE.BREVO_SMTP_EMAILS', COUNT(*) FROM BREVO.BRONZE.BREVO_SMTP_EMAILS
UNION ALL SELECT 'BREVO.BRONZE.BREVO_SMTP_EVENT', COUNT(*) FROM BREVO.BRONZE.BREVO_SMTP_EVENT
ORDER BY TABLE_NAME;
