--Database Creation 
Create database BIRD;

--Schema Creation 
Create schema BIRD.BRONZE;

--Stage Creation
CREATE OR REPLACE STAGE BIRD.BRONZE.STG_BIRD
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Bird/MessageBird event CSVs';

-- File Format Creation 
  CREATE OR REPLACE FILE FORMAT BIRD.BRONZE.FF_CSV_INFER
  TYPE = 'CSV'  PARSE_HEADER = TRUE  FIELD_OPTIONALLY_ENCLOSED_BY = '"'  SKIP_BLANK_LINES = TRUE;




--Table Creation at bronze layer
  CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_BOUNCED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_BOUNCED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_DELIVERED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_DELIVERY_FAILED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERY_FAILED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_LINK_CLICKED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_LINK_CLICKED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_MARKED_AS_SPAM USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_MARKED_AS_SPAM.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_OPENED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_OPENED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_EMAIL_UNSUBSCRIBED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_UNSUBSCRIBED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_BOUNCED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_BOUNCED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_DELIVERED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_DELIVERY_FAILED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERY_FAILED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_LINKED_CLICKED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_LINKED_CLICKED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_MARKED_SPAM USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_MARKED_SPAM.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_OPENED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_OPENED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_SKIPPED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SKIPPED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_MESSAGE_UNSUBSCRIBED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_UNSUBSCRIBED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_SUBSCRIBED_TO_LIST USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_SUBSCRIBED_TO_LIST.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_UNSUBSCRIBED_FROM_LIST USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_UNSUBSCRIBED_FROM_LIST.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_READ USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_READ.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_SENT USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_SENT.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));

CREATE OR REPLACE TABLE BIRD.BRONZE.BIRD_WHATSAPP_REPLY_CLICKED USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(INFER_SCHEMA(
    LOCATION => '@BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_REPLY_CLICKED.csv',
    FILE_FORMAT => 'BIRD.BRONZE.FF_CSV_INFER')));





-- Loading data into tables from stage

    COPY INTO BIRD.BRONZE.BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_CHAT_MESSAGE_SUCCESSFULLY_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_BOUNCED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_BOUNCED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_DELIVERED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_DELIVERY_FAILED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_DELIVERY_FAILED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_LINK_CLICKED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_LINK_CLICKED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_MARKED_AS_SPAM
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_MARKED_AS_SPAM.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_OPENED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_OPENED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_EMAIL_UNSUBSCRIBED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_EMAIL_UNSUBSCRIBED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_BOUNCED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_BOUNCED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_DELIVERED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_DELIVERY_FAILED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_DELIVERY_FAILED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_LINKED_CLICKED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_LINKED_CLICKED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_MARKED_SPAM
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_MARKED_SPAM.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_OPENED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_OPENED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_SKIPPED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_SKIPPED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_MESSAGE_UNSUBSCRIBED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_MESSAGE_UNSUBSCRIBED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_SUBSCRIBED_TO_LIST
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_SUBSCRIBED_TO_LIST.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_UNSUBSCRIBED_FROM_LIST
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_UNSUBSCRIBED_FROM_LIST.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_DELIVERY_FAILED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_READ
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_READ.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_MESSAGE_SENT
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_MESSAGE_SENT.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

COPY INTO BIRD.BRONZE.BIRD_WHATSAPP_REPLY_CLICKED
  FROM @BIRD.BRONZE.STG_BIRD/BIRD_WHATSAPP_REPLY_CLICKED.csv
  FILE_FORMAT = (TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';
